# Generated by Django 5.2.7 on 2025-11-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE public.user_movie
                ADD COLUMN user_rating SMALLINT;
                
                ALTER TABLE public.user_movie
                ADD CONSTRAINT user_movie_user_rating_check
                CHECK (user_rating >= 1 AND user_rating <= 10);
            """,
            reverse_sql="""
                ALTER TABLE public.user_movie
                DROP CONSTRAINT IF EXISTS user_movie_user_rating_check;
                
                ALTER TABLE public.user_movie
                DROP COLUMN IF EXISTS user_rating;
            """
        ),
    ]
