# Generated by Django 5.2.7 on 2025-11-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_auto_20251113_2314"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "genre",
                "managed": True,
            },
        ),
        migrations.AlterModelOptions(
            name="aisuggestionbatch",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="integrationerrorlog",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="movieavailability",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="usermovie",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="userplatform",
            options={"managed": False},
        ),
    ]
